; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=i686-- -mattr=-sse | FileCheck %s --check-prefix=ROUND
; RUN: llc < %s -mtriple=i686-- -mattr=-sse -x86-x87-round-to-type=false | FileCheck %s --check-prefix=EXCESS

; x87 registers are 80 bits wide whatever type they hold, and x87 arithmetic
; rounds to the FPU control word's precision rather than to the type of the
; value. Every f32/f64 result therefore has to be rounded back to its own type
; through memory, or an f32/f64 in a register does not hold a value of its type.

; The original miscompile: %add is compared against its own reload through
; volatile memory, so both operands must be the same f32.
define i32 @cmp_against_reload(ptr %p) nounwind {
; ROUND-LABEL: cmp_against_reload:
; ROUND:       # %bb.0:
; ROUND-NEXT:    pushl %eax
; ROUND-NEXT:    movl {{[0-9]+}}(%esp), %eax
; ROUND-NEXT:    movl $1065353216, (%eax) # imm = 0x3F800000
; ROUND-NEXT:    flds (%eax)
; ROUND-NEXT:    fadds {{\.?LCPI[0-9]+_[0-9]+}}
; ROUND-NEXT:    fstps (%esp)
; ROUND-NEXT:    flds (%esp)
; ROUND-NEXT:    fsts (%eax)
; ROUND-NEXT:    flds (%eax)
; ROUND-NEXT:    fucompp
; ROUND-NEXT:    fnstsw %ax
; ROUND-NEXT:    # kill: def $ah killed $ah killed $ax
; ROUND-NEXT:    sahf
; ROUND-NEXT:    setnp %cl
; ROUND-NEXT:    sete %dl
; ROUND-NEXT:    xorl %eax, %eax
; ROUND-NEXT:    testb %cl, %dl
; ROUND-NEXT:    jne .LBB0_2
; ROUND-NEXT:  # %bb.1:
; ROUND-NEXT:    movl $127, %eax
; ROUND-NEXT:  .LBB0_2:
; ROUND-NEXT:    popl %ecx
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: cmp_against_reload:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    movl {{[0-9]+}}(%esp), %eax
; EXCESS-NEXT:    movl $1065353216, (%eax) # imm = 0x3F800000
; EXCESS-NEXT:    flds (%eax)
; EXCESS-NEXT:    fadds {{\.?LCPI[0-9]+_[0-9]+}}
; EXCESS-NEXT:    fsts (%eax)
; EXCESS-NEXT:    flds (%eax)
; EXCESS-NEXT:    fxch %st(1)
; EXCESS-NEXT:    fucompp
; EXCESS-NEXT:    fnstsw %ax
; EXCESS-NEXT:    # kill: def $ah killed $ah killed $ax
; EXCESS-NEXT:    sahf
; EXCESS-NEXT:    setnp %cl
; EXCESS-NEXT:    sete %dl
; EXCESS-NEXT:    xorl %eax, %eax
; EXCESS-NEXT:    testb %cl, %dl
; EXCESS-NEXT:    jne .LBB0_2
; EXCESS-NEXT:  # %bb.1:
; EXCESS-NEXT:    movl $127, %eax
; EXCESS-NEXT:  .LBB0_2:
; EXCESS-NEXT:    retl
  store volatile float 1.000000e+00, ptr %p
  %ld = load volatile float, ptr %p
  %add = fadd float %ld, 0x3CB0000000000000
  store volatile float %add, ptr %p
  %rl = load volatile float, ptr %p
  %eq = fcmp oeq float %rl, %add
  %r = select i1 %eq, i32 0, i32 127
  ret i32 %r
}

define float @fadd_reg(float %a, float %b) nounwind {
; ROUND-LABEL: fadd_reg:
; ROUND:       # %bb.0:
; ROUND-NEXT:    pushl %eax
; ROUND-NEXT:    flds {{[0-9]+}}(%esp)
; ROUND-NEXT:    fadds {{[0-9]+}}(%esp)
; ROUND-NEXT:    fstps (%esp)
; ROUND-NEXT:    flds (%esp)
; ROUND-NEXT:    popl %eax
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: fadd_reg:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    flds {{[0-9]+}}(%esp)
; EXCESS-NEXT:    fadds {{[0-9]+}}(%esp)
; EXCESS-NEXT:    retl
  %r = fadd float %a, %b
  ret float %r
}

define double @fmul_reg(double %a, double %b) nounwind {
; ROUND-LABEL: fmul_reg:
; ROUND:       # %bb.0:
; ROUND-NEXT:    pushl %ebp
; ROUND-NEXT:    movl %esp, %ebp
; ROUND-NEXT:    andl $-8, %esp
; ROUND-NEXT:    subl $8, %esp
; ROUND-NEXT:    fldl 8(%ebp)
; ROUND-NEXT:    fmull 16(%ebp)
; ROUND-NEXT:    fstpl (%esp)
; ROUND-NEXT:    fldl (%esp)
; ROUND-NEXT:    movl %ebp, %esp
; ROUND-NEXT:    popl %ebp
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: fmul_reg:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    fldl {{[0-9]+}}(%esp)
; EXCESS-NEXT:    fmull {{[0-9]+}}(%esp)
; EXCESS-NEXT:    retl
  %r = fmul double %a, %b
  ret double %r
}

define float @fdiv_reg(float %a, float %b) nounwind {
; ROUND-LABEL: fdiv_reg:
; ROUND:       # %bb.0:
; ROUND-NEXT:    pushl %eax
; ROUND-NEXT:    flds {{[0-9]+}}(%esp)
; ROUND-NEXT:    fdivs {{[0-9]+}}(%esp)
; ROUND-NEXT:    fstps (%esp)
; ROUND-NEXT:    flds (%esp)
; ROUND-NEXT:    popl %eax
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: fdiv_reg:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    flds {{[0-9]+}}(%esp)
; EXCESS-NEXT:    fdivs {{[0-9]+}}(%esp)
; EXCESS-NEXT:    retl
  %r = fdiv float %a, %b
  ret float %r
}

define float @fsqrt_reg(float %a) nounwind {
; ROUND-LABEL: fsqrt_reg:
; ROUND:       # %bb.0:
; ROUND-NEXT:    pushl %eax
; ROUND-NEXT:    flds {{[0-9]+}}(%esp)
; ROUND-NEXT:    fsqrt
; ROUND-NEXT:    fstps (%esp)
; ROUND-NEXT:    flds (%esp)
; ROUND-NEXT:    popl %eax
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: fsqrt_reg:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    flds {{[0-9]+}}(%esp)
; EXCESS-NEXT:    fsqrt
; EXCESS-NEXT:    retl
  %r = call float @llvm.sqrt.f32(float %a)
  ret float %r
}

define float @fptrunc_f80(x86_fp80 %a) nounwind {
; ROUND-LABEL: fptrunc_f80:
; ROUND:       # %bb.0:
; ROUND-NEXT:    pushl %eax
; ROUND-NEXT:    fldt {{[0-9]+}}(%esp)
; ROUND-NEXT:    fstps (%esp)
; ROUND-NEXT:    flds (%esp)
; ROUND-NEXT:    popl %eax
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: fptrunc_f80:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    pushl %eax
; EXCESS-NEXT:    fldt {{[0-9]+}}(%esp)
; EXCESS-NEXT:    fstps (%esp)
; EXCESS-NEXT:    flds (%esp)
; EXCESS-NEXT:    popl %eax
; EXCESS-NEXT:    retl
  %r = fptrunc x86_fp80 %a to float
  ret float %r
}

define double @fptrunc_f80_f64(x86_fp80 %a) nounwind {
; ROUND-LABEL: fptrunc_f80_f64:
; ROUND:       # %bb.0:
; ROUND-NEXT:    pushl %ebp
; ROUND-NEXT:    movl %esp, %ebp
; ROUND-NEXT:    andl $-8, %esp
; ROUND-NEXT:    subl $8, %esp
; ROUND-NEXT:    fldt 8(%ebp)
; ROUND-NEXT:    fstpl (%esp)
; ROUND-NEXT:    fldl (%esp)
; ROUND-NEXT:    movl %ebp, %esp
; ROUND-NEXT:    popl %ebp
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: fptrunc_f80_f64:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    pushl %ebp
; EXCESS-NEXT:    movl %esp, %ebp
; EXCESS-NEXT:    andl $-8, %esp
; EXCESS-NEXT:    subl $8, %esp
; EXCESS-NEXT:    fldt 8(%ebp)
; EXCESS-NEXT:    fstpl (%esp)
; EXCESS-NEXT:    fldl (%esp)
; EXCESS-NEXT:    movl %ebp, %esp
; EXCESS-NEXT:    popl %ebp
; EXCESS-NEXT:    retl
  %r = fptrunc x86_fp80 %a to double
  ret double %r
}

define float @fptrunc_f64(double %a) nounwind {
; ROUND-LABEL: fptrunc_f64:
; ROUND:       # %bb.0:
; ROUND-NEXT:    pushl %eax
; ROUND-NEXT:    fldl {{[0-9]+}}(%esp)
; ROUND-NEXT:    fstps (%esp)
; ROUND-NEXT:    flds (%esp)
; ROUND-NEXT:    popl %eax
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: fptrunc_f64:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    pushl %eax
; EXCESS-NEXT:    fldl {{[0-9]+}}(%esp)
; EXCESS-NEXT:    fstps (%esp)
; EXCESS-NEXT:    flds (%esp)
; EXCESS-NEXT:    popl %eax
; EXCESS-NEXT:    retl
  %r = fptrunc double %a to float
  ret float %r
}

; FILD also rounds to the control word's precision, not to f32.
define float @sitofp_i32(i32 %a) nounwind {
; ROUND-LABEL: sitofp_i32:
; ROUND:       # %bb.0:
; ROUND-NEXT:    subl $8, %esp
; ROUND-NEXT:    movl {{[0-9]+}}(%esp), %eax
; ROUND-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; ROUND-NEXT:    fildl {{[0-9]+}}(%esp)
; ROUND-NEXT:    fstps (%esp)
; ROUND-NEXT:    flds (%esp)
; ROUND-NEXT:    addl $8, %esp
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: sitofp_i32:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    pushl %eax
; EXCESS-NEXT:    movl {{[0-9]+}}(%esp), %eax
; EXCESS-NEXT:    movl %eax, (%esp)
; EXCESS-NEXT:    fildl (%esp)
; EXCESS-NEXT:    popl %eax
; EXCESS-NEXT:    retl
  %r = sitofp i32 %a to float
  ret float %r
}

; Spilling an RFP32 vreg uses a 4-byte slot, so a value carrying excess
; precision would change across the call. The result must not depend on that.
define float @across_call(float %a, float %b) nounwind {
; ROUND-LABEL: across_call:
; ROUND:       # %bb.0:
; ROUND-NEXT:    subl $8, %esp
; ROUND-NEXT:    flds {{[0-9]+}}(%esp)
; ROUND-NEXT:    fadds {{[0-9]+}}(%esp)
; ROUND-NEXT:    fstps {{[0-9]+}}(%esp)
; ROUND-NEXT:    flds {{[0-9]+}}(%esp)
; ROUND-NEXT:    fstps (%esp) # 4-byte Folded Spill
; ROUND-NEXT:    calll clobber@PLT
; ROUND-NEXT:    flds (%esp) # 4-byte Folded Reload
; ROUND-NEXT:    addl $8, %esp
; ROUND-NEXT:    retl
;
; EXCESS-LABEL: across_call:
; EXCESS:       # %bb.0:
; EXCESS-NEXT:    pushl %eax
; EXCESS-NEXT:    flds {{[0-9]+}}(%esp)
; EXCESS-NEXT:    fadds {{[0-9]+}}(%esp)
; EXCESS-NEXT:    fstps (%esp) # 4-byte Folded Spill
; EXCESS-NEXT:    calll clobber@PLT
; EXCESS-NEXT:    flds (%esp) # 4-byte Folded Reload
; EXCESS-NEXT:    popl %eax
; EXCESS-NEXT:    retl
  %r = fadd float %a, %b
  call void @clobber()
  ret float %r
}

declare void @clobber()
declare float @llvm.sqrt.f32(float)
